### ISSUE TITLE
Removed.

### ISSUE THREAD

**Issue by aicastell** [jaracil/pubsub#1]

**Comment by jaracil** [comment]
Hi Ivan.
topic_len = strlen(topic) and not strlen(tm->topic)

Thanks.

2016-08-19 10:10 GMT+02:00 Angel Ivan Castell Rovira <
notifications@github.com>:

**Comment by aicastell** [comment]
Hola.  Si, me di cuenta tras publicarlo,  intente borrarlo, pero github no
deja borrar issues y la he cerrrado quitando el  comentario para no marear.
Esta aclarado. Gracias!
